name: Laravel auto deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and restart docker
        run: |
          cd /var/www/my-app
          docker compose down
          docker compose up -d --build

      - name: Run migrations
        run: |
          docker exec laravel_app php artisan migrate --force